# Generated by Django 4.2.30 on 2026-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pomodoro_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pomodoro_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('focus', 'Focusing'), ('break', 'On Break')], default='idle', max_length=20),
        ),
    ]
