PROGRAM_TRACKS = [
    {
        'id': 'foundation',
        'title': 'Негізгі дайындық',
        'faction': 'none',
        'level': '5-7 сынып',
        'lessons': 120,
        'description': 'Логика, Python негіздері, есеп шартын оқу және алғашқы олимпиадалық ойлау.',
        'outcomes': ['Есеп шартын талдау', 'Python синтаксисі', 'Қарапайым алгоритмдер', 'Бірінші диагностика'],
    },
    {
        'id': 'informatics-olympiad',
        'title': 'Информатика олимпиадасы',
        'faction': 'informatics',
        'level': 'Бастапқыдан жоғары деңгейге дейін',
        'lessons': 150,
        'description': 'C++, алгоритмдер, деректер құрылымдары, Codeforces практикасы және апталық жарыстар.',
        'outcomes': ['C++ базасы', 'Графтар және DP', 'Codeforces есептері', 'Апталық contest'],
    },
    {
        'id': 'robotics-lab',
        'title': 'Робототехника және Arduino',
        'faction': 'robotics',
        'level': 'Жоба арқылы оқу',
        'lessons': 80,
        'description': 'Arduino, датчиктер, LEGO EV3, инженерлік жобалар және командалық робот жарыстары.',
        'outcomes': ['Arduino негізі', 'Датчиктер', 'Line follower', 'Жобаны қорғау'],
    },
]

PROGRAM_ITEMS = [
    {
        'id': 'diagnostic-baseline',
        'track_id': 'foundation',
        'kind': 'diagnostic',
        'title': 'Алғашқы диагностикалық сабақ',
        'duration_minutes': 45,
        'description': 'Оқушының логикасын, код оқуын және есеп шығару деңгейін анықтау.',
        'topics': ['логика', 'енгізу/шығару', 'қысқа сұрақтар'],
        'practice': ['5 есептік диагностика', 'деңгей картасын толтыру'],
    },
    {
        'id': 'python-start',
        'track_id': 'foundation',
        'kind': 'lesson',
        'title': 'Python: енгізу, шарт, цикл',
        'duration_minutes': 60,
        'description': 'Python арқылы алғашқы есептерді шығару және кодты түсініп оқу.',
        'topics': ['input/output', 'if/else', 'for', 'while'],
        'practice': ['A+B', 'жұп/тақ', 'максимум табу'],
    },
    {
        'id': 'logic-mini-quiz',
        'track_id': 'foundation',
        'kind': 'quiz',
        'title': 'Қысқа тест: логика және күрделілік',
        'duration_minutes': 20,
        'description': 'Оқушы алгоритм қадамдарын және O(n) идеясын түсінгенін тексеру.',
        'topics': ['логика', 'Big O', 'қадам санын санау'],
        'practice': ['8 қысқа сұрақ', '2 код оқу тапсырмасы'],
    },
    {
        'id': 'week-01-logic-challenge',
        'track_id': 'foundation',
        'kind': 'contest',
        'title': '1-апта challenge: логика және шарт',
        'duration_minutes': 45,
        'description': 'Шарт, салыстыру және қарапайым симуляция есептерін бекіту.',
        'topics': ['логика', 'if/else', 'симуляция'],
        'practice': ['4 жеңіл есеп', '1 талдау сұрағы'],
    },
    {
        'id': 'week-02-python-warmup',
        'track_id': 'foundation',
        'kind': 'contest',
        'title': '2-апта challenge: Python warm-up',
        'duration_minutes': 50,
        'description': 'Цикл, санау және енгізу/шығаруға арналған қысқа жарыс.',
        'topics': ['for/while', 'counting', 'input/output'],
        'practice': ['5 Python есеп', 'қате кодты түзету'],
    },
    {
        'id': 'cpp-core',
        'track_id': 'informatics-olympiad',
        'kind': 'lesson',
        'title': 'C++ олимпиадалық шаблоны',
        'duration_minutes': 70,
        'description': 'C++ енгізу/шығару, vector, sort және contest-та қолданылатын базалық үлгі.',
        'topics': ['C++', 'vector', 'sort', 'pair'],
        'practice': ['Codeforces 800-1000', 'сұрыптау есептері'],
    },
    {
        'id': 'week-03-arrays-sprint',
        'track_id': 'informatics-olympiad',
        'kind': 'contest',
        'title': '3-апта challenge: массивтер',
        'duration_minutes': 70,
        'description': 'Массив, жиілік және сұрыптау бойынша уақытқа есеп шығару.',
        'topics': ['array', 'frequency', 'sort'],
        'practice': ['4 Codeforces есеп', '1 editorial талдау'],
    },
    {
        'id': 'week-04-greedy-sprint',
        'track_id': 'informatics-olympiad',
        'kind': 'contest',
        'title': '4-апта challenge: жадный әдіс',
        'duration_minutes': 75,
        'description': 'Жадный таңдауды дәлелдеуге және тез іске асыруға арналған жарыс.',
        'topics': ['greedy', 'sorting', 'proof'],
        'practice': ['3 есеп', '1 дәлел жазу'],
    },
    {
        'id': 'graphs-sprint',
        'track_id': 'informatics-olympiad',
        'kind': 'contest',
        'title': 'Апталық жарыс: графтар спринті',
        'duration_minutes': 90,
        'description': 'BFS/DFS тақырыптарын бекітетін қысқа командалық contest.',
        'topics': ['BFS', 'DFS', 'компоненттер', 'қысқа жол'],
        'practice': ['3 Codeforces есеп', '1 талдау есебі'],
    },
    {
        'id': 'week-06-binary-search',
        'track_id': 'informatics-olympiad',
        'kind': 'contest',
        'title': '6-апта challenge: жауап бойынша іздеу',
        'duration_minutes': 80,
        'description': 'Монотонды предикат құрып, минималды немесе максималды жауапты табу.',
        'topics': ['binary search', 'predicate', 'answer search'],
        'practice': ['3 Codeforces есеп', 'шешім идеясын жазу'],
    },
    {
        'id': 'week-07-dp-sprint',
        'track_id': 'informatics-olympiad',
        'kind': 'contest',
        'title': '7-апта challenge: DP негізі',
        'duration_minutes': 90,
        'description': 'Күй, база және ауысу арқылы динамикалық бағдарламалау есептерін шешу.',
        'topics': ['DP', 'state', 'transition'],
        'practice': ['2 жеңіл DP', '1 орташа DP'],
    },
    {
        'id': 'dp-checkpoint',
        'track_id': 'informatics-olympiad',
        'kind': 'quiz',
        'title': 'Қысқа тест: DP күйін табу',
        'duration_minutes': 25,
        'description': 'DP есептерінде күй, база және ауысуды табуды тексеру.',
        'topics': ['1D DP', '2D DP', 'күй ауысуы'],
        'practice': ['6 теория сұрағы', '2 код фрагменті'],
    },
    {
        'id': 'arduino-sensors',
        'track_id': 'robotics-lab',
        'kind': 'lesson',
        'title': 'Arduino және датчиктер',
        'duration_minutes': 75,
        'description': 'Arduino пиндері, ультрадыбыс датчигі және жарық датчигімен жұмыс.',
        'topics': ['Arduino', 'digital/analog', 'sensor', 'serial monitor'],
        'practice': ['датчик оқу', 'шекті мән қою', 'қысқа есеп'],
    },
    {
        'id': 'week-08-led-sensor',
        'track_id': 'robotics-lab',
        'kind': 'contest',
        'title': '8-апта challenge: LED және датчик',
        'duration_minutes': 60,
        'description': 'Датчик мәніне қарай LED немесе мотор әрекетін басқару.',
        'topics': ['LED', 'sensor', 'threshold'],
        'practice': ['схема жинау', 'код жазу', 'өлшеу кестесі'],
    },
    {
        'id': 'week-09-obstacle-route',
        'track_id': 'robotics-lab',
        'kind': 'contest',
        'title': '9-апта challenge: кедергіден өту',
        'duration_minutes': 75,
        'description': 'Ультрадыбыс датчигімен кедергіні байқап, робот маршрутын өзгерту.',
        'topics': ['ultrasonic sensor', 'route', 'condition'],
        'practice': ['қашықтық өлшеу', 'бұрылу логикасы', 'сынақ раунды'],
    },
    {
        'id': 'line-follower-project',
        'track_id': 'robotics-lab',
        'kind': 'project',
        'title': 'Робот жобасы: сызық қуалау',
        'duration_minutes': 120,
        'description': 'Line follower роботына логика құрып, қозғалысын тестілеу.',
        'topics': ['line sensor', 'motor control', 'PID негізі'],
        'practice': ['қозғалыс калибрлеу', 'сынақ жолы', 'жоба қорғау'],
    },
    {
        'id': 'week-10-line-calibration',
        'track_id': 'robotics-lab',
        'kind': 'contest',
        'title': '10-апта challenge: сызық датчигін баптау',
        'duration_minutes': 80,
        'description': 'Сызық датчигінің мәндерін өлшеп, тұрақты қозғалыс логикасын құру.',
        'topics': ['line sensor', 'calibration', 'motor'],
        'practice': ['мән жинау', 'шекті мән таңдау', 'трек сынағы'],
    },
    {
        'id': 'robotics-team-challenge',
        'track_id': 'robotics-lab',
        'kind': 'contest',
        'title': 'Апталық жарыс: робот маршруты',
        'duration_minutes': 90,
        'description': 'Команда роботты берілген маршруттан өткізіп, уақыт пен дәлдік бойынша жарысады.',
        'topics': ['маршрут', 'датчик', 'командалық жұмыс'],
        'practice': ['2 сынақ раунды', 'қорытынды жарыс'],
    },
    {
        'id': 'week-12-final-showcase',
        'track_id': 'robotics-lab',
        'kind': 'contest',
        'title': '12-апта challenge: финалдық жоба',
        'duration_minutes': 120,
        'description': 'Командалық робот жобасын аяқтап, нәтиже мен кодты қорғау.',
        'topics': ['team project', 'testing', 'presentation'],
        'practice': ['жоба демосы', 'қорғау', 'ұпай кестесі'],
    },
]


DEFAULT_PROGRAM_RESOURCES = [
    {
        'id': 'diagnostic-baseline-khan-logic',
        'item_id': 'diagnostic-baseline',
        'kind': 'practice',
        'title': 'Логикалық ойлау жаттығулары',
        'url': 'https://www.khanacademy.org/computing/computer-science/algorithms',
        'source': 'Khan Academy',
        'description': 'Алгоритмдік ойлауды бастапқы деңгейден тексеруге арналған қысқа түсіндірмелер мен жаттығулар.',
    },
    {
        'id': 'diagnostic-baseline-codeforces-800',
        'item_id': 'diagnostic-baseline',
        'kind': 'practice',
        'title': 'Codeforces 800 деңгейіндегі есептер',
        'url': 'https://codeforces.com/problemset?tags=800-800',
        'source': 'Codeforces',
        'description': 'Алғашқы диагностикаға жеңіл олимпиадалық есептер жиыны.',
    },
    {
        'id': 'python-start-docs',
        'item_id': 'python-start',
        'kind': 'docs',
        'title': 'Python ресми оқулығы',
        'url': 'https://docs.python.org/3/tutorial/',
        'source': 'Python Docs',
        'description': 'Python синтаксисі, шарт, цикл және функцияларды ресми түрде оқу.',
    },
    {
        'id': 'python-start-video-search',
        'item_id': 'python-start',
        'kind': 'video',
        'title': 'Python input, if, for бойынша видео іздеу',
        'url': 'https://www.youtube.com/results?search_query=python+input+if+for+beginner',
        'source': 'YouTube',
        'description': 'Оқушыға ыңғайлы видеоны таңдап көру үшін іздеу сілтемесі.',
    },
    {
        'id': 'logic-mini-quiz-big-o',
        'item_id': 'logic-mini-quiz',
        'kind': 'article',
        'title': 'Big O notation түсіндірмесі',
        'url': 'https://www.freecodecamp.org/news/big-o-cheat-sheet-time-complexity-chart/',
        'source': 'freeCodeCamp',
        'description': 'Алгоритм күрделілігін жеңіл тілмен түсінуге арналған материал.',
    },
    {
        'id': 'logic-mini-quiz-khan',
        'item_id': 'logic-mini-quiz',
        'kind': 'practice',
        'title': 'Алгоритм қадамдарын талдау',
        'url': 'https://www.khanacademy.org/computing/computer-science/algorithms',
        'source': 'Khan Academy',
        'description': 'Алгоритм қалай жұмыс істейтінін визуалды түрде түсіндіреді.',
    },
    {
        'id': 'week-01-logic-codeforces',
        'item_id': 'week-01-logic-challenge',
        'kind': 'practice',
        'title': 'Implementation 800 есептері',
        'url': 'https://codeforces.com/problemset?tags=implementation,800-800',
        'source': 'Codeforces',
        'description': 'Шарт пен қарапайым симуляцияны бекітуге арналған есептер.',
    },
    {
        'id': 'week-02-python-practice',
        'item_id': 'week-02-python-warmup',
        'kind': 'practice',
        'title': 'Python beginner practice',
        'url': 'https://www.hackerrank.com/domains/python',
        'source': 'HackerRank',
        'description': 'Цикл, шарт және енгізу/шығару бойынша интерактивті жаттығулар.',
    },
    {
        'id': 'cpp-core-cppreference',
        'item_id': 'cpp-core',
        'kind': 'docs',
        'title': 'C++ reference',
        'url': 'https://en.cppreference.com/w/cpp',
        'source': 'cppreference',
        'description': 'vector, sort, pair және STL туралы негізгі анықтамалық.',
    },
    {
        'id': 'cpp-core-usaco-guide',
        'item_id': 'cpp-core',
        'kind': 'article',
        'title': 'USACO Guide: C++ basics',
        'url': 'https://usaco.guide/general/cpp?lang=cpp',
        'source': 'USACO Guide',
        'description': 'Олимпиадалық C++ жазуға арналған қысқа әрі жүйелі нұсқаулық.',
    },
    {
        'id': 'week-03-arrays-usaco',
        'item_id': 'week-03-arrays-sprint',
        'kind': 'article',
        'title': 'USACO Guide: arrays and sorting',
        'url': 'https://usaco.guide/silver/sorting-custom?lang=cpp',
        'source': 'USACO Guide',
        'description': 'Сұрыптау және массивтер бойынша олимпиадалық тәсілдер.',
    },
    {
        'id': 'week-03-arrays-codeforces',
        'item_id': 'week-03-arrays-sprint',
        'kind': 'practice',
        'title': 'Arrays and sorting есептері',
        'url': 'https://codeforces.com/problemset?tags=sortings,800-1200',
        'source': 'Codeforces',
        'description': 'Массив, жиілік және сұрыптауды practice ету.',
    },
    {
        'id': 'week-04-greedy-cpalgorithms',
        'item_id': 'week-04-greedy-sprint',
        'kind': 'article',
        'title': 'Greedy algorithms',
        'url': 'https://cp-algorithms.com/schedules/schedule_one_machine.html',
        'source': 'cp-algorithms',
        'description': 'Жадный дәлелдеудің бір классикалық мысалы.',
    },
    {
        'id': 'week-04-greedy-codeforces',
        'item_id': 'week-04-greedy-sprint',
        'kind': 'practice',
        'title': 'Greedy 800-1200 есептері',
        'url': 'https://codeforces.com/problemset?tags=greedy,800-1200',
        'source': 'Codeforces',
        'description': 'Жадный есептерін деңгей бойынша шешу.',
    },
    {
        'id': 'graphs-sprint-cpalgorithms',
        'item_id': 'graphs-sprint',
        'kind': 'article',
        'title': 'Graph traversal: DFS және BFS',
        'url': 'https://cp-algorithms.com/graph/breadth-first-search.html',
        'source': 'cp-algorithms',
        'description': 'BFS логикасы, қысқа жол және граф аралау негіздері.',
    },
    {
        'id': 'graphs-sprint-visualgo',
        'item_id': 'graphs-sprint',
        'kind': 'tool',
        'title': 'BFS/DFS визуализациясы',
        'url': 'https://visualgo.net/en/dfsbfs',
        'source': 'VisuAlgo',
        'description': 'Граф аралауды анимация арқылы көру.',
    },
    {
        'id': 'week-06-binary-search-cpalgorithms',
        'item_id': 'week-06-binary-search',
        'kind': 'article',
        'title': 'Binary search',
        'url': 'https://cp-algorithms.com/num_methods/binary_search.html',
        'source': 'cp-algorithms',
        'description': 'Жауап бойынша бинарлық іздеудің теориясы және мысалдары.',
    },
    {
        'id': 'week-06-binary-search-practice',
        'item_id': 'week-06-binary-search',
        'kind': 'practice',
        'title': 'Binary search есептері',
        'url': 'https://codeforces.com/problemset?tags=binary%20search,800-1400',
        'source': 'Codeforces',
        'description': 'Монотонды предикатпен шешілетін есептер.',
    },
    {
        'id': 'week-07-dp-usaco',
        'item_id': 'week-07-dp-sprint',
        'kind': 'article',
        'title': 'USACO Guide: intro to DP',
        'url': 'https://usaco.guide/gold/intro-dp?lang=cpp',
        'source': 'USACO Guide',
        'description': 'DP күйі, база және ауысуды түсіндіретін жүйелі материал.',
    },
    {
        'id': 'week-07-dp-codeforces',
        'item_id': 'week-07-dp-sprint',
        'kind': 'practice',
        'title': 'DP 800-1400 есептері',
        'url': 'https://codeforces.com/problemset?tags=dp,800-1400',
        'source': 'Codeforces',
        'description': 'Динамикалық бағдарламалауды практикада бекіту.',
    },
    {
        'id': 'dp-checkpoint-cpalgorithms',
        'item_id': 'dp-checkpoint',
        'kind': 'article',
        'title': 'Dynamic programming intro',
        'url': 'https://cp-algorithms.com/dynamic_programming/intro-to-dp.html',
        'source': 'cp-algorithms',
        'description': 'DP ойлауын қысқа теориямен бекіту.',
    },
    {
        'id': 'arduino-sensors-docs',
        'item_id': 'arduino-sensors',
        'kind': 'docs',
        'title': 'Arduino documentation',
        'url': 'https://docs.arduino.cc/',
        'source': 'Arduino',
        'description': 'Arduino платалары, функциялар және датчиктер бойынша ресми құжаттама.',
    },
    {
        'id': 'arduino-sensors-tinkercad',
        'item_id': 'arduino-sensors',
        'kind': 'tool',
        'title': 'Arduino схемаларын симуляциялау',
        'url': 'https://www.tinkercad.com/circuits',
        'source': 'Tinkercad Circuits',
        'description': 'Плата жоқ кезде датчик пен схема жұмысын симуляциялау.',
    },
    {
        'id': 'week-08-led-sensor-arduino-led',
        'item_id': 'week-08-led-sensor',
        'kind': 'docs',
        'title': 'Arduino LED basics',
        'url': 'https://docs.arduino.cc/built-in-examples/basics/Blink/',
        'source': 'Arduino',
        'description': 'LED басқарудың ең қарапайым мысалы.',
    },
    {
        'id': 'week-09-obstacle-route-wokwi',
        'item_id': 'week-09-obstacle-route',
        'kind': 'tool',
        'title': 'Arduino online simulator',
        'url': 'https://wokwi.com/projects/new/arduino-uno',
        'source': 'Wokwi',
        'description': 'Arduino Uno және датчик логикасын онлайн тексеру.',
    },
    {
        'id': 'line-follower-project-pid',
        'item_id': 'line-follower-project',
        'kind': 'article',
        'title': 'PID түсінігі',
        'url': 'https://en.wikipedia.org/wiki/PID_controller',
        'source': 'Wikipedia',
        'description': 'Line follower үшін PID идеясын жалпы деңгейде түсіну.',
    },
    {
        'id': 'week-10-line-calibration-video',
        'item_id': 'week-10-line-calibration',
        'kind': 'video',
        'title': 'Line follower calibration videos',
        'url': 'https://www.youtube.com/results?search_query=line+follower+robot+calibration+arduino',
        'source': 'YouTube',
        'description': 'Сызық датчигін баптау бойынша видео сабақтарды табу.',
    },
    {
        'id': 'robotics-team-challenge-video',
        'item_id': 'robotics-team-challenge',
        'kind': 'video',
        'title': 'Arduino robot challenge examples',
        'url': 'https://www.youtube.com/results?search_query=arduino+robot+challenge+line+follower',
        'source': 'YouTube',
        'description': 'Командалық робот жарысына идея алу.',
    },
    {
        'id': 'week-12-final-showcase-guide',
        'item_id': 'week-12-final-showcase',
        'kind': 'article',
        'title': 'Жобаны таныстыру құрылымы',
        'url': 'https://www.instructables.com/projects/circuits/arduino/',
        'source': 'Instructables',
        'description': 'Arduino жобаларын құрастыру және таныстыру мысалдары.',
    },
]


def get_program_track(track_id):
    return next((track for track in PROGRAM_TRACKS if track['id'] == track_id), None)


def get_program_item(item_id):
    return next((item for item in PROGRAM_ITEMS if item['id'] == item_id), None)
