# Generated by Django 4.2.30 on 2026-05-20 13:51

from django.db import migrations, models
import django.db.models.deletion


def seed_programs(apps, schema_editor):
    ProgramTrack = apps.get_model('tasks', 'ProgramTrack')
    ProgramItem = apps.get_model('tasks', 'ProgramItem')

    from tasks.programs import PROGRAM_ITEMS, PROGRAM_TRACKS

    for order, track in enumerate(PROGRAM_TRACKS, start=1):
        ProgramTrack.objects.update_or_create(
            id=track['id'],
            defaults={
                'title': track['title'],
                'faction': track['faction'],
                'level': track['level'],
                'lessons': track['lessons'],
                'description': track['description'],
                'outcomes': track['outcomes'],
                'order': order,
                'is_active': True,
            },
        )

    for order, item in enumerate(PROGRAM_ITEMS, start=1):
        track = ProgramTrack.objects.get(id=item['track_id'])
        ProgramItem.objects.update_or_create(
            id=item['id'],
            defaults={
                'track': track,
                'kind': item['kind'],
                'title': item['title'],
                'duration_minutes': item['duration_minutes'],
                'description': item['description'],
                'topics': item['topics'],
                'practice': item['practice'],
                'order': order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTrack',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('faction', models.CharField(choices=[('informatics', 'Informatics'), ('robotics', 'Robotics'), ('none', 'None')], default='none', max_length=20)),
                ('level', models.CharField(blank=True, max_length=120)),
                ('lessons', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('lesson', 'Lesson'), ('quiz', 'Quiz'), ('contest', 'Contest'), ('project', 'Project')], default='lesson', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('description', models.TextField(blank=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('practice', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.programtrack')),
            ],
            options={
                'ordering': ['track__order', 'order', 'title'],
            },
        ),
        migrations.RunPython(seed_programs, migrations.RunPython.noop),
    ]
