# Generated by Django 4.2.30 on 2026-05-20 14:01

from django.db import migrations, models
import django.db.models.deletion


def seed_program_resources(apps, schema_editor):
    ProgramItem = apps.get_model('tasks', 'ProgramItem')
    ProgramResource = apps.get_model('tasks', 'ProgramResource')

    from tasks.programs import DEFAULT_PROGRAM_RESOURCES

    for order, resource in enumerate(DEFAULT_PROGRAM_RESOURCES, start=1):
        item = ProgramItem.objects.filter(id=resource['item_id']).first()
        if not item:
            continue

        ProgramResource.objects.update_or_create(
            id=resource['id'],
            defaults={
                'item': item,
                'kind': resource['kind'],
                'title': resource['title'],
                'url': resource['url'],
                'source': resource['source'],
                'description': resource['description'],
                'order': order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_programtrack_programitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramResource',
            fields=[
                ('id', models.SlugField(max_length=120, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('practice', 'Practice'), ('docs', 'Documentation'), ('tool', 'Tool'), ('book', 'Book')], default='article', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=600)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.programitem')),
            ],
            options={
                'ordering': ['item__track__order', 'item__order', 'order', 'title'],
            },
        ),
        migrations.RunPython(seed_program_resources, migrations.RunPython.noop),
    ]
