# Generated by Django 4.2.30 on 2026-05-19 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('index', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('todo', 'To Solve'), ('solving', 'Solving'), ('solved', 'Solved')], default='todo', max_length=20)),
                ('language', models.CharField(default='GNU C++17', max_length=50)),
                ('solution_code', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codeforces_solutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'contest_id', 'index')},
            },
        ),
    ]
