# Generated by Django 4.2.30 on 2026-05-19 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeforces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.PositiveIntegerField()),
                ('index', models.CharField(max_length=12)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('statement_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_codeforces_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contest_id', 'index'],
                'unique_together': {('contest_id', 'index')},
            },
        ),
    ]
